export const VIEW_EX_PATIENT_UP_MODAL = "VIEW_EX_PATIENT_UP_MODAL";
export const CLOSE_EX_PATIENT_UP_MODAL = "CLOSE_EX_PATIENT_UP_MODAL";

export const GET_EXISTING_PATIENT_RECORD = "GET_EXISTING_PATIENT_RECORD";
export const GET_NEW_PATIENT_FORM_RECORD = "GET_NEW_PATIENT_FORM_RECORD";

export const PATIENT_STEPS_RENDERING = "PATIENT_STEPS_RENDERING";