export const CHANGE_SLOT_VALUE="CHANGE_SLOT_VALUE";
export const SELECT_DATE="SELECT_DATE";

export const QUICK_ADD_FORM_OPEN="QUICK_ADD_FORM_OPEN"
export const QUICK_ADD_FORM_CLOSE="QUICK_ADD_FORM_CLOSE"
